include(default)
[settings]
arch=armv8
compiler=clang
compiler.libcxx=libc++
compiler.version=8
os=Android
os.api_level=21
# Must match CMAKE_BUILD_TYPE
build_type=Debug
[build_requires]
android_ndk_installer/r20@bincrafters/stable
#ninja_installer/1.8.2@bincrafters/stable
[options]
[env]
#ANDROID_NDK_ROOT=/home/conan/android-ndk-r18b
#CONAN_CACERT_PATH=...
#CXXFLAGS="-DNOMINMAX=1"
#CFLAGS=""
