include_guard( DIRECTORY )

set(CHROMIUM_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/chromium/)

set(GN_GEN_DIR ${CHROMIUM_DIR}gen/)

# generated by tools/RunGen.cmake
set(GEN_COMBINED_DIR ${GN_GEN_DIR}gen_combined/)

set(khronos_PARENT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src/chromium/third_party/)

set(khronos_DIR ${khronos_PARENT_DIR}khronos/)

# generated by tools/RunGen.cmake
#set(GEN_SERVICES_NETWORK_PUBLIC_DIR ${GN_GEN_DIR}gen_services_network_public/)

# generated by tools/RunGen.cmake
#set(GEN_BLINK_PUBLIC_DIR ${GN_GEN_DIR}gen_blink_public/)

# generated by tools/RunGen.cmake
#set(GEN_MOJO_PUBLIC_DIR ${GN_GEN_DIR}gen_mojo_public/)

# autoninja -C out/Default/ components/content_settings/core/common:mojo_bindings
set(GEN_COMPONENTS_CONTENT_SETTINGS_CORE_COMMON_DIR ${GN_GEN_DIR}gen_components_content_settings/)

# autoninja -C out/Default/ third_party/blink/renderer/core/mojo
#set(GEN_BLINK_RENDERER_CORE_DIR ${GN_GEN_DIR}gen_blink_renderer_core/)
