include_guard( DIRECTORY )

macro(find_SDL2)
  if(TARGET_EMSCRIPTEN)
    # skip
  elseif(TARGET_LINUX OR TARGET_WINDOWS)
    find_package(SDL2 REQUIRED)
    if(SDL2_FOUND)
      message("Found SDL2 libraries")
      message("SDL2_INCLUDE_DIR = ${SDL2_INCLUDE_DIR} ")
      message("SDL2_INCLUDE_DIRS = ${SDL2_INCLUDE_DIRS} ")
      message("SDL2_LIBRARY = ${SDL2_LIBRARY} ")
      add_definitions(-DUSE_SDL2_LIB)
    endif ()

    #find_package(SDL2_net REQUIRED)
    #if(SDL2_net_FOUND)
    #  message(STATUS "Found SDL2_net libraries")
    #  message(STATUS "SDL2_net_INCLUDE_DIR = ${SDL2_net_INCLUDE_DIR} ")
    #  message(STATUS "SDL2_net_LIBRARY = ${SDL2_net_LIBRARY} ")
    #  add_definitions(-DUSE_SDL2_net_LIB)
    #endif ()

    #include(sdl2/FindSDL2_ttf.cmake)
    #find_package(SDL2_ttf REQUIRED)
    #if(SDL2_ttf_FOUND)
    #  message(STATUS "Found SDL2_ttf libraries")
    #  message(STATUS "SDL2_TTF_INCLUDE_DIR = ${SDL2_TTF_INCLUDE_DIR} ")
    #  message(STATUS "SDL2_TTF_LIBRARY = ${SDL2_TTF_LIBRARY} ")
    #  add_definitions(-DUSE_SDL2_ttf_LIB)
    #endif ()
  else()
    message(FATAL_ERROR "platform not supported")
  endif()
endmacro(find_SDL2)
