#pragma once

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ALTERNATE_CDM_STORAGE_ID_KEY() ()
#define BUILDFLAG_INTERNAL_ENABLE_AC3_EAC3_AUDIO_DEMUXING() (0)
#define BUILDFLAG_INTERNAL_ENABLE_CBCS_ENCRYPTION_SCHEME() (0)
#define BUILDFLAG_INTERNAL_ENABLE_CDM_HOST_VERIFICATION() (0)
#define BUILDFLAG_INTERNAL_ENABLE_CDM_STORAGE_ID() (0)
#define BUILDFLAG_INTERNAL_ENABLE_DAV1D_DECODER() (0)
#define BUILDFLAG_INTERNAL_ENABLE_AV1_DECODER() (0)
#define BUILDFLAG_INTERNAL_ENABLE_DOLBY_VISION_DEMUXING() (0)
#define BUILDFLAG_INTERNAL_ENABLE_FFMPEG() (0)
#define BUILDFLAG_INTERNAL_ENABLE_FFMPEG_VIDEO_DECODERS() (0)
#define BUILDFLAG_INTERNAL_ENABLE_HEVC_DEMUXING() (0)
#define BUILDFLAG_INTERNAL_ENABLE_HLS_SAMPLE_AES() (0)
#define BUILDFLAG_INTERNAL_ENABLE_LIBRARY_CDMS() (0)
#define BUILDFLAG_INTERNAL_ENABLE_LIBVPX() (0)
#define BUILDFLAG_INTERNAL_ENABLE_LOGGING_OVERRIDE() (0)
#define BUILDFLAG_INTERNAL_ENABLE_MEDIA_REMOTING() (0)
#define BUILDFLAG_INTERNAL_ENABLE_MEDIA_REMOTING_RPC() (0)
#define BUILDFLAG_INTERNAL_ENABLE_MPEG_H_AUDIO_DEMUXING() (0)
#define BUILDFLAG_INTERNAL_ENABLE_MSE_MPEG2TS_STREAM_PARSER() (0)
#define BUILDFLAG_INTERNAL_USE_PROPRIETARY_CODECS() (0)
